### ISSUE TITLE
Atomic Tablebases Incorrectly Assessing Insufficient Mating Material

### ISSUE THREAD

**Issue by sabfrompc** [niklasf/lila-tablebase#1]
I know this is the wrong place to post this, but hopefully someone else knows where it should be posted.

At the end of the game, it was a mate in seven, despite the tablebase saying it was a draw. There are likely other issues as well, so it might be worth someone else going through and double checking, since there's not really much point in having a tablebase if it's not accurate.
https://lichess.org/zM5LfgKL

**Comment by niklasf** [comment]
Thanks for reporting, fixed.

This was a bug in my chess library, where I incorrectly detected insufficient material before even asking the tablebase, so fortunately the tablebase itself is fine.

More testing is of course always good. I guess standard chess received most of my attention.

Edit: Note that the incorrect tablebase results might remain in browser cache for a while.
