### ISSUE TITLE
What's the rate limit for `/standard` endpoint?

### ISSUE THREAD

**Issue by eduherminio** [niklasf/lila-tablebase#158]
I'm integrating an option for my bot to use the online tablebase and would like to know what's the rate limit for the /standard endpoint in order to configure a proper retry (exponential backoff) policy.

I already figured out it's way less strict than `/standard/mainline` one (confirmed in https://github.com/lichess-org/lila-tablebase/issues/61), but would love get some numbers.

**Comment by niklasf** [comment]
The exact limits aren't documented anywhere, because they are subject to change as needed. 1 second *between* requests should be safe.

**Comment by eduherminio** [comment]
1 second between requests is good enough for root position probing, but definitely not for search probing then.
