### ISSUE TITLE
`maybe-win` and `maybe-loss` categories

### ISSUE THREAD

**Issue by eduherminio** [niklasf/lila-tablebase#159]
Positions that should return `maybe-win` ("8/6B1/6B1/8/2K2n2/4k3/8/8 w - - 1 2", [here](https://github.com/lichess-org/lila-tablebase/blob/7673693118d8cf7fc151b2d70c012e8e4cf60862/test.py#L91-L94)) and `maybe-loss` ("K7/2k5/3n4/8/2b5/8/8/8 w - - 97 128"), [here](https://github.com/lichess-org/lila-tablebase/blob/7673693118d8cf7fc151b2d70c012e8e4cf60862/test.py#L44C22-L48) according to the tests don't seem to return it in the prod endpoint.

Are those categories still in use?
If that's the case, when do positions get assigned those categories? Any chance some real examples could be provided to better understand and handle them?

Thanks!

**Comment by niklasf** [comment]
For up to and including 6 pieces, tablebase.lichess.ovh uses a modified set of tables that never yield ambiguous results. [DTZ rounding](https://syzygy-tables.info/metrics#dtz) is still used, but only for 7 piece tables.

Here's an example: https://tablebase.lichess.ovh/standard?fen=8/8/1p6/8/P1P3k1/P7/P6K/8_b_-_-_66_1

Testing locally with 7 piece tables would be unwieldy, so the tests are written for the official Syzygy tablebases, where even 4 piece endgames can have such ambiguities.

**Comment by eduherminio** [comment]
Makes sense, thanks!
