### ISSUE TITLE
Problems with connection to tablebaseserver

### ISSUE THREAD

**Issue by Yosgarat** [niklasf/lila-tablebase#165]
Hello,
I have problems with connecting to the tabelbase on following URI:

http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1

It seems like the Server is down or not available.
There is also a report that the Lichess-Client also can't connect.
https://lichess.org/forum/lichess-feedback/cannot-open-tablebase
I tested the connection via Postman to validate my problems.

This was the response:
```
GET http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1: {
  "Error": "connect ECONNREFUSED 54.37.255.147:80",
  "Request Headers": {
    "user-agent": "PostmanRuntime/7.33.0",
    "accept": "*/*",
    "postman-token": "8ac11b1d-73a6-4163-ba18-e8ed75d9fb1c",
    "host": "tablebase.lichess.ovh",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  }
}
```
Please check if the server is down or is in any trouble. I hope I could help.

**Comment by Yosgarat** [comment]
Seems that the server was only short unavailable.

**Comment by niklasf** [comment]
Yep, a failed disk had to be replaced.
