### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/lila-tablebase#2]
Hi many, many thanks for all your great work.
One tiny suggestion :-) As a problem composer, most of the interaction I have with the board is seeing what the change would be if I shift a piece to a new square. However, if that shift happens to randomly correspond to a legal move, then the player to move will be flipped. This is really disconcerting.
I am wondering if you could have two modes "Play" and "Explore". "Play" is what you have right now, but "Explore" only changes the player to move if you select the move from the menu on the right (or change the player to move explicitly at the top.

**Comment by niklasf** [comment]
Hi, thanks, I didn't think about that use case. Moving to the repo of the syzyg-tables.info UI.
